(function(){
  angular
    .module('zephyr')
    .factory('AirlineFactory', AirlineFactory);

  function AirlineFactory() {
    var factory = {};

    factory.airlines = {
      "M3" : "ABSA Cargo Airline",
      "JP" : "Adria Airways",
      "A3" : "Aegean Airlines",
      "EI" : "Aer Lingus",
      "NG" : "Aero Contractors",  
      "P5" : "Aero República",  
      "SU" : "Aeroflot",  
      "AR" : "Aerolineas Argentinas",
      "2K" : "Aerolineas Galapagos S.A. Aerogal",
      "AM" : "Aeromexico",
      "8U" : "Afriqiyah Airways",
      "ZI" : "Aigle Azur",
      "AH" : "Air Algérie",
      "G9" : "Air Arabia",
      "KC" : "Air Astana",
      "UU" : "Air Austral",
      "BT" : "Air Baltic",
      "AB" : "Air Berlin",
      "BP" : "Air Botswana",
      "TY" : "Air Caledonie",
      "AC" : "Air Canada",
      "CA" : "Air China Limited",
      "XK" : "Air Corsica",
      "UX" : "Air Europa",
      "AF" : "Air France",
      "AI" : "Air India",
      "JS" : "Air Koryo",
      "NX" : "Air Macau",
      "MD" : "Air Madagascar",
      "KM" : "Air Malta",
      "MK" : "Air Mauritius",
      "9U" : "Air Moldova",
      "SW" : "Air Namibia",
      "NZ" : "Air New Zealand",
      "PX" : "Air Niugini",
      "YW" : "Air Nostrum",
      "JU" : "Air SERBIA a.d. Beograd",
      "HM" : "Air Seychelles",
      "VT" : "Air Tahiti",
      "TN" : "Air Tahiti Nui",
      "TS" : "Air Transat",
      "NF" : "Air Vanuatu",
      "RU" : "AirBridgeCargo Airlines",
      "SB" : "Aircalin",
      "4Z" : "Airlink",
      "AS" : "Alaska Airlines",
      "AZ" : "Alitalia",
      "NH" : "All Nippon Airways",
      "UJ" : "AlMasria Universal Airlines",
      "K4" : "ALS",
      "AA" : "American Airlines",
      "W3" : "Arik Air",
      "IZ" : "Arkia Israeli Airlines",
      "OZ" : "Asiana",
      "5Y" : "Atlas Air",
      "KK" : "Atlasjet Airlines",
      "AU" : "Austral",
      "OS" : "Austrian",
      "AV" : "AVIANCA",
      "O6" : "Avianca Brasil",
      "J2" : "Azerbaijan Airlines", 
      "AD" : "Azul Brazilian Airlines",
      "PG" : "Bangkok Air",
      "B2" : "Belavia - Belarusian Airlines",
      "8H" : "BH AIR",
      "BG" : "Biman",
      "NT" : "Binter Canarias",
      "BV" : "Blue Panorama",
      "KF" : "Blue1",
      "BM" : "bmi Regional",
      "OB" : "Boliviana de Aviación - BoA",
      "BA" : "British Airways", 
      "SN" : "Brussels Airlines",
      "FB" : "Bulgaria air",
      "5C" : "C.A.L. Cargo Airlines",
      "W8" : "Cargojet Airways",
      "CV" : "Cargolux S.A.",
      "BW" : "Caribbean Airlines",
      "V3" : "Carpatair",
      "CX" : "Cathay Pacific",
      "CI" : "China Airlines",
      "CK" : "China Cargo Airlines",
      "MU" : "China Eastern",
      "CF" : "China Postal Airlines",
      "CZ" : "China Southern Airlines",
      "WX" : "CityJet",
      "MN" : "Comair",
      "DE" : "Condor",
      "CM" : "COPA Airlines",
      "XC" : "Corendon Airlines",
      "SS" : "Corsair International",
      "OU" : "Croatia Airlines",
      "CU" : "Cubana",
      "CY" : "Cyprus Airways",
      "OK" : "Czech Airlines j.s.c",
      "DL" : "Delta Air Lines",
      "D0" : "DHL Air",
      "D9" : "Donavia",
      "KA" : "Dragonair",
      "MS" : "Egyptair",
      "EK" : "Emirates", 
      "OV" : "Estonian Air",
      "ET" : "Ethiopian Airlines",
      "EY" : "Etihad Airways",
      "YU" : "Euroatlantic Airways",
      "QY" : "European Air Transport",
      "EW" : "Eurowings",
      "BR" : "EVA Air",
      "FX" : "Federal Express",
      "FJ" : "Fiji Airways", 
      "AY" : "Finnair",
      "BE" : "flybe",
      "FH" : "Freebird Airlines",
      "GA" : "Garuda",
      "A9" : "Georgian Airways",
      "ST" : "Germania",
      "GF" : "Gulf Air",
      "HU" : "Hainan Airlines",
      "HA" : "Hawaiian Airlines",
      "5K" : "Hi Fly",
      "HX" : "Hong Kong Airlines",
      "UO" : "Hong Kong Express Airways",
      "IB" : "IBERIA",
      "FI" : "Icelandair",
      "7I" : "InselAir",
      "D6" : "Interair",
      "4O" : "Interjet",
      "3L" : "InterSky",
      "IR" : "Iran Air",
      "EP" : "Iran Aseman Airlines",
      "6H" : "Israir",
      "JL" : "Japan Airlines",
      "J9" : "Jazeera Airways",
      "9W" : "Jet Airways",
      "S2" : "Jet Lite (India) Limited",
      "B6" : "JetBlue",
      "R5" : "Jordan Aviation",
      "R3" : "JSC Aircompany Yakutia",
      "5N" : "JSC Nordavia-RA",
      "HO" : "Juneyao Airlines",
      "KQ" : "Kenya Airways",
      "Y9" : "Kish Air",
      "KE" : "Korean Air",
      "KU" : "Kuwait Airways",
      "LR" : "LACSA",
      "TM" : "LAM", 
      "LA" : "Lan Airlines",
      "4M" : "Lan Argentina",
      "UC" : "Lan Cargo",
      "LP" : "Lan Perú",
      "XL" : "LanEcuador",
      "LI" : "LIAT Airlines",
      "N4" : "LLC NORD WIND",
      "LO" : "LOT Polish Airlines",
      "LH" : "Lufthansa",
      "CL" : "Lufthansa CityLine",
      "LG" : "Luxair",
      "W5" : "Mahan Air",
      "MH" : "Malaysia Airlines",
      "TF" : "Malmö Aviation",
      "MP" : "Martinair Cargo",
      "M7" : "MAS AIR",
      "IG" : "Meridiana fly", 
      "OM" : "MIAT",
      "YM" : "Montenegro Airlines",
      "NE" : "Nesma Airlines",
      "HG" : "NIKI",
      "NP" : "Nile Air",
      "KZ" : "Nippon Cargo Airlines (NCA)",
      "BJ" : "Nouvelair",
      "OA" : "Olympic Air",
      "WY" : "Oman Air",
      "8Q" : "Onur Air", 
      "R2" : "Orenair",
      "PR" : "PAL",
      "PC" : "Pegasus Airlines",
      "NI" : "PGA-Portugália Airlines",
      "PK" : "PIA",
      "PW" : "Precision Air",
      "PV" : "PrivatAir",
      "QF" : "Qantas",
      "QR" : "Qatar Airways",
      "FV" : "Rossiya Airlines",
      "AT" : "Royal Air Maroc",
      "BI" : "Royal Brunei",
      "RJ" : "Royal Jordanian",
      "WB" : "RwandAir",
      "SA" : "SAA",
      "4Q" : "Safi Airways",
      "S3" : "Santa Barbara",
      "SK" : "SAS",
      "SP" : "SATA Air Açores",
      "S4" : "SATA Internacional",
      "SV" : "Saudi Arabian Airlines",
      "SC" : "Shandong Airlines",
      "FM" : "Shanghai Airlines",
      "ZH" : "Shenzhen Airlines",
      "SQ" : "SIA",
      "S7" : "Siberia Airlines",
      "3U" : "Sichuan Airlines",
      "MI" : "Silkair",
      "H2" : "SKY Airline",
      "XZ" : "South African Express Airways",
      "UL" : "SriLankan",
      "SD" : "Sudan Airways",
      "PY" : "Surinam Airways",
      "LX" : "SWISS",
      "FS" : "SYPHAX AIRLINES",
      "RB" : "Syrianair",
      "DT" : "TAAG - Angola Airlines",
      "TA" : "TACA",
      "T0" : "TACA Peru",
      "VR" : "TACV Cabo Verde Airlines",
      "PZ" : "TAM - Transportes Aéreos del Mercosur Sociedad Anónima",
      "JJ" : "TAM Linhas Aéreas",
      "EQ" : "TAME - Linea Aérea del Ecuador",
      "TP" : "TAP Portugal",
      "RO" : "TAROM",
      "SF" : "Tassili Airlines",
      "TG" : "Thai Airways International",
      "TK" : "THY - Turkish Airlines",
      "GS" : "Tianjin Airlines",
      "3V" : "TNT Airways S.A.",
      "UN" : "Transaero",
      "GE" : "TransAsia Airways",
      "TU" : "Tunisair",
      "PS" : "Ukraine International Airlines",
      "UA" : "United Airlines",
      "5X" : "UPS Airlines",
      "US" : "US Airways",
      "UT" : "UTair",
      "HY" : "Uzbekistan Airways",
      "VN" : "Vietnam Airlines",
      "VS" : "Virgin Atlantic",
      "VA" : "Virgin Australia",
      "VG" : "VLM Airlines",
      "G3" : "VRG Linhas Aéreas S.A. - Grupo GOL",
      "WF" : "Wideroe",
      "MF" : "Xiamen Airlines",
      "IY" : "Yemenia"
    };

    return factory;
  }
})();