(function(){
  angular
    .module('zephyr')
    .factory('AirportFactory', AirportFactory);

  function AirportFactory() {
    var factory = {};

    factory.airports = {
      "BHM" : "Birmingham International Airport",
      "DHM" : "Dothan Regional Airport",
      "HSV" : "Huntsville International Airport",
      "MOB" : "Mobile Airport",
      "MGM" : "Montgomery Airport",
      "ANC" : "Anchorage International Airport",
      "FAI" : "Fairbanks International Airport",
      "JNU" : "Juneau International Airport",
      "FLG" : "Flagstaff Airport",
      "PHX" : "Phoenix, Phoenix Sky Harbor International Airport",
      "TUS" : "Tucson International Airport",
      "YUM" : "Yuma International Airport",
      "FYV" : "Fayetteville Airport",
      "LIT" : "Little Rock National Airport",
      "BUR" : "Burbank Airport",
      "FAT" : "Fresno Airport",
      "LGB" : "Long Beach Airport",
      "LAX" : "Los Angeles International Airport",
      "OAK" : "Oakland Airport",
      "ONT" : "Ontario Airport",
      "PSP" : "Palm Springs Airport",
      "SMF" : "Sacramento Airport",
      "SAN" : "San Diego Airport",
      "SFO" : "San Francisco International Airport",
      "SJC" : "San Jose Airport",
      "SNA" : "Santa Ana Airport",
      "ASE" : "Aspen Airport",
      "COS" : "Colorado Springs Airport",
      "DEN" : "Denver International Airport",
      "GJT" : "Grand Junction Airport",
      "PUB" : "Pueblo Airport",
      "BDL" : "Hartford Airport",
      "IAD" : "Washington, Dulles International Airport",
      "DCA" : "Washington National Airport",
      "DAB" : "Daytona Beach Airport",
      "FLL" : "Fort Lauderdale-Hollywood International Airport",
      "RSW" : "Fort Meyers Airport",
      "JAX" : "Jacksonville Airport",
      "MIA" : "Miami International Airport",
      "MCO" : "Orlando Airport",
      "PNS" : "Pensacola Airport",
      "PIE" : "St. Petersburg Airport",
      "SRQ" : "Sarasota Airport",
      "TPA" : "Tampa Airport",
      "PBI" : "West Palm Beach Airport",
      "PFN" : "Panama City-Bay County International Airport",
      "ATL" : "Atlanta Hartsfield International Airport",
      "AGS" : "Augusta Airport",
      "SAV" : "Savannah Airport",
      "ITO" : "Hilo Airport",
      "HNL" : "Honolulu International Airport",
      "OGG" : "Kahului Airport",
      "KOA" : "Kailua Airport",
      "LIH" : "Lihue Airport",
      "BOI" : "Boise Airport",
      "MDW" : "Chicago Midway Airport",
      "ORD" : "Chicago, O'Hare International Airport Airport",
      "MLI" : "Moline Airport",
      "PIA" : "Peoria Airport",  
      "EVV" : "Evansville Airport",
      "FWA" : "Fort Wayne Airport",
      "IND" : "Indianapolis International Airport",
      "SBN" : "South Bend Airport",
      "CID" : "Cedar Rapids Airport",
      "DSM" : "Des Moines Airport",
      "ICT" : "Wichita Airport",
      "LEX" : "Lexington Airport",
      "SDF" : "Louisville Airport",
      "BTR" : "Baton Rouge Airport",
      "MSY" : "New Orleans International Airport",
      "SHV" : "Shreveport Airport",
      "AUG" : "Augusta Airport",
      "BGR" : "Bangor Airport",
      "PWM" : "Portland Airport",
      "BWI" : "Baltimore Airport",
      "BOS" : "Boston, Logan International Airport",
      "HYA" : "Hyannis Airport",
      "ACK" : "Nantucket Airport",
      "ORH" : "Worcester Airport",
      "BTL" : "Battlecreek Airport",
      "DTW" : "Detroit Metropolitan Airport",
      "DET" : "Detroit Airport",
      "FNT" : "Flint Airport",
      "GRR" : "Grand Rapids Airport",
      "AZO" : "Kalamazoo-Battle Creek International Airport",
      "LAN" : "Lansing Airport",
      "MBS" : "Saginaw Airport",
      "DLH" : "Duluth Airport",
      "MSP" : "Minneapolis/St.Paul International Airport",
      "RST" : "Rochester Airport",
      "GPT" : "Gulfport Airport",
      "JAN" : "Jackson Airport",
      "MCI" : "Kansas City Airport",
      "STL" : "St Louis, Lambert International Airport",
      "SGF" : "Springfield Airport",
      "BIL" : "Billings Airport",
      "LNK" : "Lincoln Airport",
      "OMA" : "Omaha Airport",
      "LAS" : "Las Vegas, Las Vegas McCarran International Airport",
      "RNO" : "Reno-Tahoe International Airport",
      "MHT" : "Manchester Airport",
      "ACY" : "Atlantic City International Airport",
      "EWR" : "Newark International Airport",
      "TTN" : "Trenton Airport",
      "ABQ" : "Albuquerque International Airport",
      "ALM" : "Alamogordo Airport",
      "ALB" : "Albany International Airport",
      "BUF" : "Buffalo Airport",
      "ISP" : "Islip Airport",
      "JFK" : "New York, John F Kennedy International Airport",
      "LGA" : "New York, La Guardia Airport",
      "SWF" : "Newburgh Airport",
      "ROC" : "Rochester Airport",
      "SYR" : "Syracuse Airport",
      "HPN" : "Westchester Airport",
      "AVL" : "Asheville Airport",
      "CLT" : "Charlotte/Douglas International Airport",
      "FAY" : "Fayetteville Airport",
      "GSO" : "Greensboro Airport",
      "RDU" : "Raleigh Airport",
      "INT" : "Winston-Salem Airport",
      "BIS" : "Bismark Airport",
      "FAR" : "Fargo Airport",
      "CAK" : "Akron Airport",
      "CVG" : "Cincinnati Airport",
      "CLE" : "Cleveland Airport",
      "CMH" : "Columbus Airport",
      "DAY" : "Dayton Airport",
      "TOL" : "Toledo Airport",
      "OKC" : "Oklahoma City Airport",
      "TUL" : "Tulsa Airport",
      "EUG" : "Eugene Airport",
      "PDX" : "Portland International Airport",
      "HIO" : "Portland, Hillsboro Airport",
      "SLE" : "Salem Airport",
      "ABE" : "Allentown Airport",
      "ERI" : "Erie Airport",
      "MDT" : "Harrisburg Airport",
      "PHL" : "Philadelphia Airport",
      "PIT" : "Pittsburgh Airport",
      "AVP" : "Scranton Airport",
      "PVD" : "Providence - T.F. Green Airport",
      "CHS" : "Charleston Airport",
      "CAE" : "Columbia Airport",
      "GSP" : "Greenville Airport",
      "MYR" : "Myrtle Beach Airport",
      "PIR" : "Pierre Airport",
      "RAP" : "Rapid City Airport",
      "FSD" : "Sioux Falls Airport",
      "TRI" : "Bristol Airport",
      "CHA" : "Chattanooga Airport",
      "TYS" : "Knoxville Airport",
      "MEM" : "Memphis Airport",
      "BNA" : "Nashville Airport",
      "AMA" : "Amarillo Airport",
      "AUS" : "Austin Bergstrom International Airport",
      "CRP" : "Corpus Christi Airport",
      "DAL" : "Dallas Love Field Airport",
      "DFW" : "Dallas/Fort Worth International Airport",
      "ELP" : "El Paso Airport",
      "HOU" : "Houston, William B Hobby Airport",
      "IAH" : "Houston, George Bush Intercontinental Airport",
      "LBB" : "Lubbock Airport",
      "MAF" : "Midland Airport",
      "SAT" : "San Antonio International Airport",
      "SLC" : "Salt Lake City Airport",
      "BTV" : "Burlington Airport",
      "MPV" : "Montpelier Airport",
      "RUT" : "Rutland Airport",
      "PHF" : "Newport News Airport",
      "ORF" : "Norfolk Airport",
      "RIC" : "Richmond Airport",
      "ROA" : "Roanoke Airport",
      "PSC" : "Pasco, Pasco/Tri-Cities Airport",
      "SEA" : "Seattle, Tacoma International Airport",
      "GEG" : "Spokane International Airport",
      "CRW" : "Charleston Airport",
      "CKB" : "Clarksburg Airport",
      "GRB" : "Green Bay Airport",
      "MSN" : "Madison Airport",
      "MKE" : "Milwaukee Airport",
      "CPR" : "Casper Airport",
      "CYS" : "Cheyenne Airport",
      "JAC" : "Jackson Hole Airport",
      "RKS" : "Rock Springs Airport"
    };

    return factory;
  }
})();